apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-sensorsreport-tls
  namespace: default
spec:
  secretName: www-sensorsreport-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer      # <--- this is the key difference
  dnsNames:
  - www.sensorsreport.net

